export type Lang = 'ru' | 'en'

/**
 * Shape of one language's dictionary.
 *
 * Declared explicitly (instead of `typeof dict.ru`) so that `dict.ru` and
 * `dict.en` are both assignable to `Dict` — `as const` would otherwise make
 * the literal types ("Главная" vs "Home") incompatible and break
 * `getDict(lang): Dict` in i18n-server.ts.
 */
export type Dict = {
  nav: Record<'home' | 'catalog' | 'icons' | 'builder' | 'billing' | 'admin' | 'account' | 'myPacks', string>
  hero: Record<string, string>
  features: Record<string, string>
  pricing: Record<string, string>
  footer: Record<string, string>
  faq: Record<string, string>
  catalog: Record<string, string>
  packView: Record<string, string>
  customize: Record<string, string>
  builder: Record<string, string>
  account: Record<string, string>
  admin: Record<string, string>
  billing: Record<string, string>
  common: Record<string, string>
  toast: Record<string, string>
}

export const dict: Record<Lang, Dict> = {
  ru: {
    nav: {
      home: 'Главная',
      catalog: 'Паки',
      icons: 'Иконки',
      builder: 'Сборка',
      billing: 'Тарифы',
      admin: 'Админка',
      account: 'Кабинет',
      myPacks: 'Мои паки',
    },
    hero: {
      badge: 'SVG-иконки для веб-разработки',
      title: 'Паки SVG-иконок',
      titleAccent: 'для современных интерфейсов',
      subtitle: 'Скачивайте бесплатные паки или кастомизируйте цвет, толщину, размер, фон и поворот — за копейки по подписке, кредитам или разово.',
      ctaPrimary: 'Открыть каталог',
      ctaSecondary: 'Собрать свой пак',
      stat1: '745 иконок',
      stat1Label: 'в 18 паков',
      stat2: '6 опций',
      stat2Label: 'кастомизации',
      stat3: 'RU/EN',
      stat3Label: 'мультиязычность',
    },
    features: {
      title: 'Что внутри',
      subtitle: 'Бесплатные паки + платная кастомизация под ваш бренд',
      f1Title: 'Бесплатные паки',
      f1Desc: '745 иконок в 18 тематических паков: языки, фреймворки, инструменты, концепты. Скачивайте отдельные SVG или zip-архивом.',
      f2Title: 'Кастомизация',
      f2Desc: 'Цвет, толщина линий, размер, фон/подложка, поворот, двухцветный duotone-режим — применяйте к целому паку или одной иконке.',
      f3Title: '3 типа оплаты',
      f3Desc: 'Разовая покупка пака, ежемесячная подписка на все паки или кредиты с расходованием по факту — выбирайте удобный формат.',
      f4Title: 'Сборка пака',
      f4Desc: 'Соберите свой пак из иконок разных тематик — скачайте одним архивом или сохраните в личном кабинете.',
      f5Title: 'Copy SVG',
      f5Desc: 'Скопируйте код любой иконки в буфер в один клик — бесплатно, без регистрации.',
      f6Title: 'Мультиязычность',
      f6Desc: 'Интерфейс на русском и английском, переключается мгновенно и сохраняет выбор.',
    },
    pricing: {
      title: 'Тарифы',
      subtitle: 'Бесплатно навсегда + платные опции для профи',
      free: 'Бесплатно',
      freePrice: '0 ₽',
      freeDesc: 'Попробуйте все возможности без карты',
      freeF1: 'Скачивание всех паков в исходном виде',
      freeF2: '3 сборки своего пака в месяц',
      freeF3: '10 кредитов в подарок при регистрации',
      freeCta: 'Начать бесплатно',
      oneTime: 'Разово',
      oneTimePrice: 'от 25 ₽',
      oneTimeDesc: 'Покупка кастомизации одного пака или иконки навсегда',
      oneTimeF1: '1 пак = 149 ₽',
      oneTimeF2: '1 иконка = 25 ₽',
      oneTimeF3: 'Хранится в кабинете навсегда',
      oneTimeCta: 'Купить разово',
      sub: 'Подписка',
      subPrice: '200 ₽/мес',
      subDesc: 'Безлимитная кастомизация всех паков и иконок',
      subF1: 'Все паки без ограничений',
      subF2: 'Безлимит сборки своих паков',
      subF3: 'Приоритет новых паков',
      subCta: 'Подписаться',
      credits: 'Кредиты',
      creditsPrice: '100 кр. = 149 ₽',
      creditsDesc: 'Платите по факту: 1 кастомизация = 5 кредитов',
      creditsF1: 'Не сгорают',
      creditsF2: '20 кастомизаций за 149 ₽',
      creditsF3: 'Подходит для редких задач',
      creditsCta: 'Купить кредиты',
      note: 'Демо-режим: оплата заглушкой, реальная интеграция появится позже.',
      detailsLink: 'Подробнее о тарифах →',
    },
    footer: {
      tagline: 'SVG-иконки для современных интерфейсов',
      productTitle: 'Продукт',
      resourcesTitle: 'Ресурсы',
      companyTitle: 'Компания',
      license: 'Лицензия MIT',
      contacts: 'Контакты',
      catalog: 'Каталог',
      builder: 'Собрать пак',
      pricing: 'Тарифы',
      copyright: '© 2026 SVG Stack Hub',
    },
    faq: {
      title: 'Частые вопросы',
      q1: 'Паки действительно бесплатные?',
      a1: 'Да, все паков в каталоге можно скачать в исходном виде бесплатно — без регистрации. Платить нужно только за кастомизацию (цвет, толщина, фон и т.д.).',
      q2: 'Можно ли использовать иконки в коммерческих проектах?',
      a2: 'Да, все иконки можно использовать в личных и коммерческих проектах без указания авторства. Перепродажа самих иконок как отдельного продукта запрещена.',
      q3: 'Что произойдёт с моими кастомизированными иконками после окончания подписки?',
      a3: 'Все ранее скачанные и сохранённые иконки остаются у вас навсегда. Подписка нужна только для создания новых кастомизаций.',
      q4: 'Можно ли получить кредиты бесплатно?',
      a4: 'При регистрации начисляется 10 кредитов в подарок. Дополнительно можно получать кредиты за отзывы и репосты (скоро).',
      q5: 'Какие форматы экспорта поддерживаются?',
      a5: 'SVG-файлы по одной, zip-архив со всеми иконками пака или SVG-спрайт с <symbol> для подключения через <use>.',
    },
    catalog: {
      title: 'Каталог паков',
      subtitle: 'Выберите пак, чтобы посмотреть все иконки и скачать',
      searchPlaceholder: 'Поиск иконок по названию или тегам...',
      filterAll: 'Все',
      filterLanguages: 'Языки',
      filterFrameworks: 'Фреймворки',
      filterTools: 'Инструменты',
      filterConcepts: 'Концепты',
      filterEducation: 'Образование',
      iconsCount: 'иконок',
      viewPack: 'Открыть',
      downloadZip: 'Скачать ZIP',
      noResults: 'Ничего не найдено',
    },
    packView: {
      back: '← Назад к каталогу',
      downloadPack: 'Скачать пак (ZIP)',
      customizePack: 'Кастомизировать пак',
      copySvg: 'Скопировать SVG',
      downloadSvg: 'Скачать SVG',
      add: 'В сборку',
      added: '✓ Добавлено',
    },
    customize: {
      title: 'Кастомизатор',
      subtitle: 'Применяйте изменения ко всему паку или отдельной иконке',
      color: 'Цвет',
      strokeWidth: 'Толщина линий',
      size: 'Размер экспорта',
      background: 'Фон',
      bgNone: 'Нет',
      bgCircle: 'Круг',
      bgSquare: 'Квадрат',
      bgColor: 'Цвет фона',
      rotation: 'Поворот',
      mode: 'Режим',
      modeMono: 'Моно',
      modeDuotone: 'Двухцветный',
      color2: 'Второй цвет',
      locked: 'Платная опция',
      preview: 'Предпросмотр',
      applyToPack: 'Применить ко всему паку',
      applyToIcon: 'Применить к этой иконке',
      scopeMode: 'Область применения',
      scopeAll: 'Все',
      scopeSingle: 'По одной',
      scopeMulti: 'Несколько',
      scopeAllHint: 'Одни настройки для всех иконок в паке',
      scopeSingleHint: 'Кликните иконку, чтобы править её отдельно',
      scopeMultiHint: 'Выделите иконки кликом — настройки применятся к выбранным',
      selected: 'Выбрано',
      edited: 'Изменено',
      resetAll: 'Сбросить все переопределения',
      cost: 'Стоимость',
      credits: 'кредитов',
      pay: 'Оплатить и сохранить',
      needPay: 'Нужно оплатить',
      free: 'Бесплатно',
      reset: 'Сбросить',
    },
    builder: {
      title: 'Сборка своего пака',
      subtitle: 'Добавляйте иконки из любых паков в свою коллекцию',
      empty: 'Сборка пуста. Откройте пак и нажмите «В сборку».',
      download: 'Скачать мой пак (ZIP)',
      save: 'Сохранить в мои паки',
      saveName: 'Название пака',
      clear: 'Очистить',
      count: 'в сборке',
      saved: 'Пак сохранён!',
    },
    account: {
      title: 'Личный кабинет',
      email: 'Email',
      credits: 'Кредиты',
      plan: 'Текущий план',
      planFree: 'Бесплатный',
      planSub: 'Подписка',
      history: 'История покупок',
      empty: 'Покупок пока нет',
      logout: 'Выйти',
      login: 'Войти как демо-пользователь',
      adminLink: 'Перейти в админку',
      downloadsLeft: 'Скачиваний осталось',
      open: 'Открыть',
    },
    admin: {
      title: 'Админ-панель',
      subtitle: 'Управление паками и иконками',
      statsPacks: 'Паки',
      statsIcons: 'Иконки',
      statsUsers: 'Пользователи',
      statsRevenue: 'Доход (демо)',
      packs: 'Паки',
      icons: 'Иконки',
      newPack: 'Новый пак',
      editPack: 'Редактировать пак',
      packNameRu: 'Название (RU)',
      packNameEn: 'Название (EN)',
      packDescRu: 'Описание (RU)',
      packDescEn: 'Описание (EN)',
      packSlug: 'Slug',
      packCategory: 'Категория',
      packStyle: 'Стиль',
      packTags: 'Теги (через запятую)',
      packPrice: 'Цена в кредитах',
      packFree: 'Бесплатный',
      save: 'Сохранить',
      cancel: 'Отмена',
      delete: 'Удалить',
      addIcon: 'Добавить иконку',
      iconSlug: 'Slug',
      iconNameRu: 'Название (RU)',
      iconNameEn: 'Название (EN)',
      iconKeywords: 'Ключевые слова',
      iconSvg: 'SVG-содержимое (внутри <svg>)',
      svgHint: 'Например: <path d="..." />',
    },
    billing: {
      title: 'Биллинг',
      balance: 'Ваш баланс',
      credits: 'кредитов',
      buyCredits: 'Купить кредиты',
      buyPack: 'Купить кастомизацию пака',
      subscribe: 'Оформить подписку',
      active: 'Активна',
      notActive: 'Не активна',
      history: 'История транзакций',
      amount: 'Сумма',
      type: 'Тип',
      date: 'Дата',
      empty: 'Транзакций нет',
    },
    common: {
      langSwitch: 'RU/EN',
      login: 'Войти',
      ctaStart: 'Начать',
      language: 'Язык',
      demoMode: 'Демо-режим',
    },
    toast: {
      copied: 'SVG скопирован в буфер',
      added: 'Иконка добавлена в сборку',
      downloaded: 'Скачивание началось',
      saved: 'Сохранено',
      paid: 'Оплата прошла (демо)',
      noCredits: 'Недостаточно кредитов',
      error: 'Что-то пошло не так',
    },
  },
  en: {
    nav: {
      home: 'Home',
      catalog: 'Packs',
      icons: 'Icons',
      builder: 'Builder',
      billing: 'Pricing',
      admin: 'Admin',
      account: 'Account',
      myPacks: 'My Packs',
    },
    hero: {
      badge: 'SVG icons for web dev',
      title: 'SVG icon packs',
      titleAccent: 'for modern interfaces',
      subtitle: 'Download free packs or customize color, stroke, size, background and rotation — for pennies via subscription, credits, or one-time.',
      ctaPrimary: 'Browse catalog',
      ctaSecondary: 'Build your pack',
      stat1: '745 icons',
      stat1Label: 'in 18 packs',
      stat2: '6 options',
      stat2Label: 'to customize',
      stat3: 'RU/EN',
      stat3Label: 'i18n',
    },
    features: {
      title: "What's inside",
      subtitle: 'Free packs + paid customization for your brand',
      f1Title: 'Free packs',
      f1Desc: '745 icons in 18 themed packs: languages, frameworks, tools, concepts. Download individual SVGs or as a zip archive.',
      f2Title: 'Customization',
      f2Desc: 'Color, stroke width, size, background, rotation, duotone two-color mode — apply to a whole pack or a single icon.',
      f3Title: '3 payment types',
      f3Desc: 'One-time pack purchase, monthly subscription to all packs, or pay-as-you-go credits — choose what fits.',
      f4Title: 'Pack builder',
      f4Desc: 'Mix icons from different packs into your own collection — download as a zip or save to your account.',
      f5Title: 'Copy SVG',
      f5Desc: 'Copy any icon code to clipboard in one click — free, no signup.',
      f6Title: 'Multi-language',
      f6Desc: 'Interface in Russian and English, instant switch with persistence.',
    },
    pricing: {
      title: 'Pricing',
      subtitle: 'Free forever + paid options for pros',
      free: 'Free',
      freePrice: '0 ₽',
      freeDesc: 'Try every feature, no card required',
      freeF1: 'Download all packs in original form',
      freeF2: '3 pack builds per month',
      freeF3: '10 credits gift on signup',
      freeCta: 'Start free',
      oneTime: 'One-time',
      oneTimePrice: 'from 25 ₽',
      oneTimeDesc: 'Buy customization of one pack or icon forever',
      oneTimeF1: '1 pack = 149 ₽',
      oneTimeF2: '1 icon = 25 ₽',
      oneTimeF3: 'Stored in account forever',
      oneTimeCta: 'Buy one-time',
      sub: 'Subscription',
      subPrice: '200 ₽/mo',
      subDesc: 'Unlimited customization of all packs and icons',
      subF1: 'All packs unlimited',
      subF2: 'Unlimited pack builder',
      subF3: 'Priority new packs',
      subCta: 'Subscribe',
      credits: 'Credits',
      creditsPrice: '100 cr = 149 ₽',
      creditsDesc: 'Pay as you go: 1 customization = 5 credits',
      creditsF1: 'Never expire',
      creditsF2: '20 customizations for 149 ₽',
      creditsF3: 'For occasional tasks',
      creditsCta: 'Buy credits',
      note: 'Demo mode: mock payment, real integration coming later.',
      detailsLink: 'More about pricing →',
    },
    footer: {
      tagline: 'SVG icons for modern interfaces',
      productTitle: 'Product',
      resourcesTitle: 'Resources',
      companyTitle: 'Company',
      license: 'MIT License',
      contacts: 'Contacts',
      catalog: 'Catalog',
      builder: 'Build Pack',
      pricing: 'Pricing',
      copyright: '© 2026 SVG Stack Hub',
    },
    faq: {
      title: 'FAQ',
      q1: 'Are packs really free?',
      a1: 'Yes, all packs in the catalog can be downloaded in their original form for free — no signup. You only pay for customization (color, stroke, background, etc.).',
      q2: 'Can I use icons in commercial projects?',
      a2: 'Yes, all icons can be used in personal and commercial projects without attribution. Reselling icons as a standalone product is prohibited.',
      q3: 'What happens to my customized icons after subscription ends?',
      a3: 'All previously downloaded and saved icons remain with you forever. Subscription is only needed for new customizations.',
      q4: 'Can I get credits for free?',
      a4: '10 credits are gifted on signup. Additional credits for reviews and shares (coming soon).',
      q5: 'What export formats are supported?',
      a5: 'Individual SVG files, zip archive with all pack icons, or SVG sprite with <symbol> for <use> embedding.',
    },
    catalog: {
      title: 'Pack catalog',
      subtitle: 'Pick a pack to see all icons and download',
      searchPlaceholder: 'Search icons by name or tags...',
      filterAll: 'All',
      filterLanguages: 'Languages',
      filterFrameworks: 'Frameworks',
      filterTools: 'Tools',
      filterConcepts: 'Concepts',
      filterEducation: 'Education',
      iconsCount: 'icons',
      viewPack: 'Open',
      downloadZip: 'Download ZIP',
      noResults: 'No results',
    },
    packView: {
      back: '← Back to catalog',
      downloadPack: 'Download pack (ZIP)',
      customizePack: 'Customize pack',
      copySvg: 'Copy SVG',
      downloadSvg: 'Download SVG',
      add: 'Add to build',
      added: '✓ Added',
    },
    customize: {
      title: 'Customizer',
      subtitle: 'Apply changes to the whole pack or a single icon',
      color: 'Color',
      strokeWidth: 'Stroke width',
      size: 'Export size',
      background: 'Background',
      bgNone: 'None',
      bgCircle: 'Circle',
      bgSquare: 'Square',
      bgColor: 'Background color',
      rotation: 'Rotation',
      mode: 'Mode',
      modeMono: 'Mono',
      modeDuotone: 'Duotone',
      color2: 'Second color',
      locked: 'Paid option',
      preview: 'Preview',
      applyToPack: 'Apply to whole pack',
      applyToIcon: 'Apply to this icon',
      scopeMode: 'Scope',
      scopeAll: 'All',
      scopeSingle: 'Per icon',
      scopeMulti: 'Multi',
      scopeAllHint: 'One config for every icon in the pack',
      scopeSingleHint: 'Click an icon to edit it individually',
      scopeMultiHint: 'Click icons to select — config applies to selected',
      selected: 'selected',
      edited: 'edited',
      resetAll: 'Reset all overrides',
      cost: 'Cost',
      credits: 'credits',
      pay: 'Pay & save',
      needPay: 'Payment required',
      free: 'Free',
      reset: 'Reset',
    },
    builder: {
      title: 'Pack builder',
      subtitle: 'Add icons from any pack to your collection',
      empty: 'Build is empty. Open a pack and click "Add to build".',
      download: 'Download my pack (ZIP)',
      save: 'Save to my packs',
      saveName: 'Pack name',
      clear: 'Clear',
      count: 'in build',
      saved: 'Pack saved!',
    },
    account: {
      title: 'Account',
      email: 'Email',
      credits: 'Credits',
      plan: 'Current plan',
      planFree: 'Free',
      planSub: 'Subscription',
      history: 'Purchase history',
      empty: 'No purchases yet',
      logout: 'Log out',
      login: 'Log in as demo user',
      adminLink: 'Go to admin',
      downloadsLeft: 'Downloads left',
      open: 'Open',
    },
    admin: {
      title: 'Admin panel',
      subtitle: 'Manage packs and icons',
      statsPacks: 'Packs',
      statsIcons: 'Icons',
      statsUsers: 'Users',
      statsRevenue: 'Revenue (demo)',
      packs: 'Packs',
      icons: 'Icons',
      newPack: 'New pack',
      editPack: 'Edit pack',
      packNameRu: 'Name (RU)',
      packNameEn: 'Name (EN)',
      packDescRu: 'Description (RU)',
      packDescEn: 'Description (EN)',
      packSlug: 'Slug',
      packCategory: 'Category',
      packStyle: 'Style',
      packTags: 'Tags (comma-separated)',
      packPrice: 'Price in credits',
      packFree: 'Free',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      addIcon: 'Add icon',
      iconSlug: 'Slug',
      iconNameRu: 'Name (RU)',
      iconNameEn: 'Name (EN)',
      iconKeywords: 'Keywords',
      iconSvg: 'SVG content (inside <svg>)',
      svgHint: 'E.g. <path d="..." />',
    },
    billing: {
      title: 'Billing',
      balance: 'Your balance',
      credits: 'credits',
      buyCredits: 'Buy credits',
      buyPack: 'Buy pack customization',
      subscribe: 'Subscribe',
      active: 'Active',
      notActive: 'Not active',
      history: 'Transaction history',
      amount: 'Amount',
      type: 'Type',
      date: 'Date',
      empty: 'No transactions',
    },
    common: {
      langSwitch: 'RU/EN',
      login: 'Log in',
      ctaStart: 'Get started',
      language: 'Language',
      demoMode: 'Demo mode',
    },
    toast: {
      copied: 'SVG copied to clipboard',
      added: 'Icon added to build',
      downloaded: 'Download started',
      saved: 'Saved',
      paid: 'Payment succeeded (demo)',
      noCredits: 'Not enough credits',
      error: 'Something went wrong',
    },
  },
}
